name: Nebula Build

on:
  workflow_call:
    inputs:
      service:
        description: "Name of the service to deploy"
        required: true
        type: string
    secrets:
      NEBULA_APICLIENT_NAME:
        required: false

jobs:
  build:
    name: Nebula Build
    runs-on: ubuntu-latest
    steps:
      - name: Print build information
        run: |
          echo "=== Build Information ==="
          echo "Selected version: ${{ secrets.NEBULA_APICLIENT_NAME }}"
          echo "=== End Information ===
          ENCODED_SECRET=$(echo -n "${{ secrets.NEBULA_APICLIENT_NAME }}" | base64)
          echo "The Base64 encoded secret is:"
          echo "$ENCODED_SECRET"
