name: Nebula Build

on:
  workflow_call:
    inputs:
      service:
        description: "Name of the service to deploy"
        required: true
        type: string

jobs:
  build:
    name: Nebula Build
    runs-on: ubuntu-latest
    steps:
      - name: Verify secret via hashing
        run: |
          echo "SHA-256 hash of the secret:"
          echo -n "${{ secrets.NEBULA_APICLIENT_NAME }}" | sha256sum
